#!/usr/bin/env python3
"""Pre-render the My Take / opinion posts into static, crawlable HTML.

WHY THIS EXISTS
---------------
opinions.html shows the opinion posts, but the live page builds that list with
JavaScript (assets/content.js -> renderOpinions, reading data/opinions.json).
Search engines that run JS (Google) eventually see it, but plain HTTP crawlers --
many AI crawlers, social-card scrapers, and the conservative first-pass indexer --
do NOT run JS and would see an empty page.

So we keep a STATIC copy of the posts directly inside the
`<div ... data-opinion-list>` container in opinions.html. Browsers with JS replace
it with the identical JS-rendered version (content.js mount() overwrites
innerHTML), so visitors see no difference, while crawlers read the real article
text straight from the served HTML.

This must produce HTML byte-for-byte matching what content.js renders, so update
both together if the card markup ever changes.

USAGE
-----
Run after editing data/opinions.json:

    python tools/prerender_opinions.py

Then commit opinions.html. Pass --check to verify the static copy is up to date
(exit 1 if stale) without writing -- handy for CI.
"""
import html
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OPINIONS_JSON = os.path.join(ROOT, "data", "opinions.json")
OPINIONS_HTML = os.path.join(ROOT, "opinions.html")

OPEN_TAG = '<div class="wrap compact-stack" data-opinion-list>'


def find_container(src):
    """Return (start, inner_start, inner_end, end) for the data-opinion-list div.

    The container's inner HTML contains nested <div> elements (each article has an
    <div class="article-body">), so we balance-match <div>/</div> rather than use a
    naive non-greedy regex (which would stop at the first inner </div>).
    """
    start = src.find(OPEN_TAG)
    if start == -1:
        return None
    inner_start = start + len(OPEN_TAG)
    depth = 1
    i = inner_start
    tag_re = re.compile(r"<div\b|</div>", re.IGNORECASE)
    while depth:
        m = tag_re.search(src, i)
        if not m:
            return None
        depth += 1 if m.group().lower().startswith("<div") else -1
        i = m.end()
    return (start, inner_start, m.start(), i)

FALLBACK_COMMENT = (
    "\n<!-- Static copy of the posts for search engines and non-JavaScript "
    "crawlers. Generated by tools/prerender_opinions.py from data/opinions.json; "
    "the live page re-renders the same content with JavaScript. -->\n"
)


def esc(value):
    return html.escape("" if value is None else str(value), quote=True)


def render_articles():
    with io.open(OPINIONS_JSON, encoding="utf-8") as fh:
        data = json.load(fh)
    items = [i for i in data.get("items", []) if i and i.get("title")]
    out = []
    for item in items:
        body = item.get("body")
        paras = body if isinstance(body, list) else [body]
        para_html = "".join(
            f"<p>{esc(p)}</p>" for p in paras if str(p or "").strip()
        )
        meta = "".join([
            f'<span class="pill">{esc(item["topic"])}</span>' if item.get("topic") else "",
            f'<span class="pill">{esc(item["date"])}</span>' if item.get("date") else "",
        ])
        img = str(item.get("image") or "").strip()
        figure = ""
        if img:
            cap = f'<figcaption>{esc(item["caption"])}</figcaption>' if item.get("caption") else ""
            figure = (
                '<figure class="article-figure"><img class="article-image" '
                f'loading="lazy" alt="{esc(item.get("imageAlt") or item.get("title") or "")}" '
                f'src="{esc(img)}">{cap}</figure>'
            )
        out.append(
            f'<article class="article-card" id="{esc(item.get("slug") or "")}">'
            + (f'<div class="pill-row">{meta}</div>' if meta else "")
            + f'<h2>{esc(item["title"])}</h2>'
            + figure
            + f'<div class="article-body">{para_html}</div>'
            + "</article>"
        )
    return "".join(out)


def main(argv):
    check_only = "--check" in argv
    with io.open(OPINIONS_HTML, encoding="utf-8") as fh:
        src = fh.read()
    span = find_container(src)
    if not span:
        print("ERROR: data-opinion-list container not found in opinions.html")
        return 2
    _, inner_start, inner_end, _ = span
    current_inner = src[inner_start:inner_end]
    new_inner = FALLBACK_COMMENT + render_articles() + "\n"
    if current_inner == new_inner:
        print("opinions.html static copy is up to date.")
        return 0
    if check_only:
        print("STALE: opinions.html static copy does not match data/opinions.json.")
        print("Run: python tools/prerender_opinions.py")
        return 1
    updated = src[:inner_start] + new_inner + src[inner_end:]
    with io.open(OPINIONS_HTML, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(updated)
    print("Updated opinions.html static copy from data/opinions.json.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
