#!/usr/bin/env python3
"""Pre-render JS-injected page content into static, crawlable HTML.

WHY THIS EXISTS
---------------
Several public pages build their visible content with JavaScript at runtime
(assets/games.js, assets/content.js) by fetching data/*.json. Browsers that run
JS (real visitors, Googlebot eventually) see the full content. But plain HTTP
crawlers -- most AI crawlers (GPTBot, ClaudeBot, PerplexityBot, etc.), social-card
scrapers, and the conservative first-pass indexer -- do NOT run JS and would see an
empty hero-only page.

So we keep a STATIC copy of the real content directly inside the SAME container the
JS targets. On load the JS replaces that container's innerHTML with the identical
rendered version, so visitors see no difference, while non-JS crawlers read the real
content straight from the served HTML.

This tool regenerates those static copies from the JSON so they stay in sync. Run it
after editing the underlying data, then commit the changed HTML.

PAGES HANDLED
-------------
  games.html  <div ... data-games-list>        from data/games.json  (the big Game
                                                Archive: ~1220 franchises / 4550 game
                                                entries -- the priority content)
  news.html   <div ... data-gaming-news-list>  from data/gaming_news.json
  guides.html <div ... data-guides-list>       from guide/packs/index.json
  setup.html  <div ... data-setup-list>        from data/setups.json
  faq.html    <div ... data-faq-list>          from data/faq.json

(opinions.html is handled by the sibling tools/prerender_opinions.py.)

MEASURED GAP (2026-07-25) -- why guides/setup/faq were added
------------------------------------------------------------
Audited every JS-injected container on the site for how much text a non-JS crawler
actually receives. games/news/opinions were already covered; the rest shipped EMPTY:

    games.html    data-games-list          297,835 words   CRAWLABLE
    opinions.html data-opinion-list          4,458 words   CRAWLABLE
    news.html     data-gaming-news-list        482 words   CRAWLABLE
    guides.html   data-guides-list               2 words   EMPTY  <- 110 guide packs
    setup.html    data-setup-list                2 words   EMPTY  <- 20 KB of settings
    faq.html      data-faq-list                  0 words   EMPTY
    schedule.html data-schedule-list             0 words   EMPTY  (see note below)
    games.html    data-playlog-list              0 words   EMPTY  (see note below)

guides is the worst loss: 110 spoiler-free guide packs -- the site's actual
differentiator -- were invisible to every non-JS crawler, so nothing linked into the
per-pack guides either.

NOT handled here, deliberately (no silent omissions):
  - schedule.html / data-playlog-list: their JSON is transient state (235 B / 339 B,
    "upcoming" is normally empty). Prerendering a stale schedule is worse than an
    empty one, so these stay JS-only by choice.
  - guide/?pack=<id> itself is still one JS shell for all 110 packs. Making each pack
    a crawlable URL is a bigger change (real per-pack pages + sitemap) and is NOT done
    here -- guides.html now at least links every pack so they are discoverable.

USAGE
-----
    python tools/prerender_site.py            # rewrite the static copies
    python tools/prerender_site.py --check    # exit 1 if any copy is stale (CI)
"""
import html
import io
import json
import os
import re
import sys
from urllib.parse import quote

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def esc(value):
    return html.escape("" if value is None else str(value), quote=True)


def find_container(src, open_tag):
    """Return (inner_start, inner_end) for a balanced <div ...> ... </div> block.

    Balance-matches <div>/</div> so nested divs inside the container are handled
    (a naive non-greedy regex would stop at the first inner </div>).
    """
    start = src.find(open_tag)
    if start == -1:
        return None
    inner_start = start + len(open_tag)
    depth = 1
    i = inner_start
    tag_re = re.compile(r"<div\b|</div>", re.IGNORECASE)
    while depth:
        m = tag_re.search(src, i)
        if not m:
            return None
        depth += 1 if m.group().lower().startswith("<div") else -1
        i = m.end()
    return (inner_start, m.start())


def fallback_comment(source_json):
    # source_json is normally a bare name under data/, but a page may source from
    # elsewhere in the tree (guides.html reads guide/packs/index.json) -- keep the
    # comment pointing at the REAL path so the provenance is not a lie.
    src = source_json if "/" in source_json else "data/" + source_json
    src = os.path.normpath(src).replace(os.sep, "/").lstrip("./")
    return (
        "\n<!-- Static copy for search engines and non-JavaScript crawlers. "
        f"Generated by tools/prerender_site.py from {src}; the live "
        "page re-renders the same content with JavaScript. -->\n"
    )


# --------------------------------------------------------------------------- #
# Game Archive (games.html, data/games.json)
# --------------------------------------------------------------------------- #

def _game_entry_html(franchise, entry):
    """One crawlable <details> per game entry.

    Carries the headline, searchable content an AI crawler/search engine needs to
    understand the Game Archive: every game's title + franchise + year, the primary
    "best version to play" verdict (platform + version + why), the definitive edition,
    and any fidelity-vs-completeness conflict, plus Sami's own sheet. We deliberately
    omit the longest secondary prose (full how-to-play walls, the per-platform release
    map, emulation notes) so the whole 4550-entry page stays a sane size; the live
    games.js still renders all of that for visitors. This static copy only has to be
    readable by non-JS crawlers, not byte-identical to the JS output (the JS overwrites
    the entire list on load).
    """
    title = entry.get("title") or "Untitled"
    year = entry.get("release_year")
    summary_line = (
        f"<small>{esc(franchise)}"
        + (f" &middot; {esc(year)}" if year else "")
        + f"</small> <strong>{esc(title)}</strong>"
    )
    parts = [f"<summary>{summary_line}</summary>", "<div class=\"game-entry-body\">"]

    sami = entry.get("sami") or {}
    sami_rows = []
    for label, key in (
        ("Chosen platform", "chosen_platform"),
        ("Rating", "rating"),
        ("Difficulty", "difficulty"),
        ("Completion", "completion_date"),
    ):
        val = str(sami.get(key) or "").strip()
        if val:
            sami_rows.append(f"<p><strong>{esc(label)}</strong> <span>{esc(val)}</span></p>")
    notes = str(sami.get("notes") or "").strip()
    if sami_rows or notes:
        parts.append("<section><h3>Sami sheet</h3>" + "".join(sami_rows)
                     + (f"<blockquote>{esc(notes)}</blockquote>" if notes else "")
                     + "</section>")

    primary = entry.get("primary") or {}
    if any(str(primary.get(k) or "").strip() for k in ("version", "platform", "why")):
        p = ["<section><h3>Primary full run</h3>"]
        if primary.get("version") or primary.get("platform"):
            p.append(f"<h4>{esc(primary.get('version') or primary.get('platform'))}</h4>")
        if primary.get("platform"):
            p.append(f"<p><strong>{esc(primary['platform'])}</strong></p>")
        if primary.get("why"):
            p.append(f"<p>{esc(primary['why'])}</p>")
        p.append("</section>")
        parts.append("".join(p))

    conflict = entry.get("fidelity_vs_completeness_conflict") or {}
    if conflict.get("exists") and conflict.get("note"):
        parts.append(f"<section><h3>Fidelity vs completeness conflict</h3><p>{esc(conflict['note'])}</p></section>")

    if str(entry.get("definitive_edition") or "").strip():
        parts.append(f"<section><h3>Definitive edition</h3><p>{esc(entry['definitive_edition'])}</p></section>")

    parts.append("</div>")
    return "<details class=\"game-entry\">" + "".join(parts) + "</details>"


def render_games():
    with io.open(os.path.join(ROOT, "data", "games.json"), encoding="utf-8") as fh:
        data = json.load(fh)
    franchises = data if isinstance(data, list) else []
    out = []
    for fr in franchises:
        label = fr.get("franchise") or ""
        summary = str(fr.get("summary") or "").strip()
        entries = [e for e in (fr.get("entries") or []) if e and e.get("title")]
        if not entries:
            continue
        section = [f'<section class="franchise-group"><h2>{esc(label)}</h2>']
        if summary:
            section.append(f"<p>{esc(summary)}</p>")
        for entry in entries:
            section.append(_game_entry_html(label, entry))
        section.append("</section>")
        out.append("".join(section))
    return "".join(out)


# --------------------------------------------------------------------------- #
# Gaming News & Rumors (news.html, data/gaming_news.json)
# --------------------------------------------------------------------------- #

def _rumor_odds_bar(probability):
    pct = max(0, min(100, round(float(probability or 0))))
    return (
        f'<div class="rumor-odds" role="img" aria-label="{pct}% likely to be true">'
        f'<div class="pill-row"><span class="pill">{pct}% likely true</span></div>'
        '<div style="position:relative;height:10px;border-radius:999px;overflow:hidden;'
        'border:1px solid var(--line);background:color-mix(in srgb, var(--surface-2) 72%, transparent);'
        'margin-top:8px">'
        f'<span style="position:absolute;inset:0 {100 - pct}% 0 0;'
        'background:linear-gradient(90deg, var(--accent), var(--accent-2));border-radius:999px"></span>'
        '</div></div>'
    )


def _news_card(item):
    is_rumor = str(item.get("type") or "").lower() == "rumor"
    meta = [f'<span class="pill">{esc("Rumor" if is_rumor else "News")}</span>']
    for key in ("game", "source", "date"):
        if item.get(key):
            meta.append(f'<span class="pill">{esc(item[key])}</span>')
    bar = _rumor_odds_bar(item.get("probability")) if is_rumor else ""
    return (
        '<article class="article-card">'
        + f'<div class="pill-row">{"".join(meta)}</div>'
        + f'<h2>{esc(item.get("title"))}</h2>'
        + f'<div class="article-body"><p>{esc(item.get("summary"))}</p></div>'
        + bar
        + '</article>'
    )


def render_news():
    with io.open(os.path.join(ROOT, "data", "gaming_news.json"), encoding="utf-8") as fh:
        data = json.load(fh)
    items = [i for i in (data.get("items") or []) if i and i.get("title")]
    return "".join(_news_card(i) for i in items)


# --------------------------------------------------------------------------- #
# Spoiler-free guide library (guides.html, guide/packs/index.json)
# --------------------------------------------------------------------------- #

def render_guides():
    """One crawlable <a> per guide pack, mirroring guides.html's own card() markup.

    Only the pack TITLE and its guide URL are emitted -- never pack CONTENT. The whole
    point of the guides is that they stay spoiler-gated until the reader asks, so a
    static copy that dumped requirement text would leak exactly what the gate protects.
    """
    with io.open(os.path.join(ROOT, "guide", "packs", "index.json"), encoding="utf-8") as fh:
        data = json.load(fh)
    out = []
    for pack in (data.get("packs") or []):
        pid, title = pack.get("id"), pack.get("title")
        if not pid or not title:
            continue
        href = "guide/?pack=" + quote(str(pid), safe="")
        out.append(
            f'<a class="card guide-card" href="{esc(href)}">'
            '<span class="pill">Spoiler-free</span>'
            f"<h3>{esc(title)}</h3>"
            '<p class="sub">100% completion &mdash; every collectible, secret, and all '
            "endings in one run.</p>"
            '<span class="guide-open">Open guide &#8594;</span>'
            "</a>"
        )
    return "".join(out)


# --------------------------------------------------------------------------- #
# Game settings & mods (setup.html, data/setups.json)
# --------------------------------------------------------------------------- #

def _setup_block(block):
    """A titled prose block (HDR write-up / NVIDIA App / DLSS swap)."""
    if not isinstance(block, dict) or not block.get("title"):
        return ""
    parts = [f"<h3>{esc(block['title'])}</h3>"]
    if block.get("intro"):
        parts.append(f"<p>{esc(block['intro'])}</p>")
    for para in (block.get("paragraphs") or []):
        parts.append(f"<p>{esc(para)}</p>")
    for item in (block.get("settings") or []):
        if isinstance(item, dict) and item.get("label"):
            parts.append(
                f"<p><strong>{esc(item['label'])}</strong> "
                f"<span>{esc(item.get('value'))}</span></p>"
            )
    return "<section>" + "".join(parts) + "</section>"


def _setup_card(game):
    title = game.get("title") or "Untitled"
    parts = [f'<article class="card setup-card" id="game-{esc(game.get("id") or "")}">']

    meta = []
    if game.get("status"):
        meta.append(f'<span class="pill">{esc(game["status"])}</span>')
    if game.get("rig"):
        meta.append(f'<span class="pill subtle">{esc(game["rig"])}</span>')
    if meta:
        parts.append(f'<div class="pill-row">{"".join(meta)}</div>')

    parts.append(f"<h2>{esc(title)}</h2>")
    if game.get("summary"):
        parts.append(f"<p>{esc(game['summary'])}</p>")

    for group in (game.get("groups") or []):
        if not isinstance(group, dict) or not group.get("name"):
            continue
        rows = "".join(
            f"<p><strong>{esc(s.get('label'))}</strong> <span>{esc(s.get('value'))}</span></p>"
            for s in (group.get("settings") or []) if isinstance(s, dict) and s.get("label")
        )
        parts.append(f"<section><h3>{esc(group['name'])}</h3>{rows}</section>")

    for key in ("hdrWriteup", "nvidia", "dlss"):
        parts.append(_setup_block(game.get(key)))

    if game.get("settingsNote"):
        parts.append(f"<p><small>{esc(game['settingsNote'])}</small></p>")

    mods = [m for m in (game.get("mods") or []) if isinstance(m, dict) and m.get("name")]
    if mods:
        rows = "".join(
            f"<p><strong>{esc(m['name'])}</strong> <span>{esc(m.get('note'))}</span></p>"
            for m in mods
        )
        parts.append(f'<div class="setup-mods"><h3>Mods</h3>{rows}</div>')
    if game.get("modsNote"):
        parts.append(f"<p><small>{esc(game['modsNote'])}</small></p>")

    parts.append("</article>")
    return "".join(parts)


def render_setups():
    with io.open(os.path.join(ROOT, "data", "setups.json"), encoding="utf-8") as fh:
        data = json.load(fh)
    games = [g for g in (data.get("games") or []) if isinstance(g, dict) and g.get("title")]
    return "".join(_setup_card(g) for g in games)


# --------------------------------------------------------------------------- #
# FAQ (faq.html, data/faq.json)
# --------------------------------------------------------------------------- #

def render_faq():
    """Mirrors content.js renderFaq(): <details class="faq-item">.

    Q&A is disproportionately valuable to read-only AI crawlers, which is most of the
    traffic this static copy exists for.
    """
    with io.open(os.path.join(ROOT, "data", "faq.json"), encoding="utf-8") as fh:
        data = json.load(fh)
    out = []
    for item in (data.get("items") or []):
        if not isinstance(item, dict) or not item.get("question"):
            continue
        out.append(
            '<details class="faq-item">'
            f"<summary>{esc(item['question'])}</summary>"
            f"<p>{esc(item.get('answer'))}</p>"
            "</details>"
        )
    return "".join(out)


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #

PAGES = [
    ("games.html", '<div class="wrap games-list" data-games-list>', "games.json", render_games),
    ("news.html", '<div class="wrap compact-stack" data-gaming-news-list>', "gaming_news.json", render_news),
    ("guides.html", '<div class="wrap games-list" data-guides-list>', "../guide/packs/index.json", render_guides),
    ("setup.html", '<div class="wrap" data-setup-list>', "setups.json", render_setups),
    ("faq.html", '<div class="wrap compact-stack" data-faq-list>', "faq.json", render_faq),
]


def process(page, open_tag, source_json, renderer, check_only):
    path = os.path.join(ROOT, page)
    with io.open(path, encoding="utf-8") as fh:
        src = fh.read()
    span = find_container(src, open_tag)
    if not span:
        print(f"ERROR: container not found in {page}: {open_tag}")
        return 2
    inner_start, inner_end = span
    current = src[inner_start:inner_end]
    new_inner = fallback_comment(source_json) + renderer() + "\n"
    if current == new_inner:
        print(f"{page} static copy is up to date.")
        return 0
    label = source_json if "/" in source_json else "data/" + source_json
    label = os.path.normpath(label).replace(os.sep, "/").lstrip("./")
    if check_only:
        print(f"STALE: {page} static copy does not match {label}.")
        return 1
    updated = src[:inner_start] + new_inner + src[inner_end:]
    with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(updated)
    print(f"Updated {page} static copy from {label}.")
    return 0


def main(argv):
    check_only = "--check" in argv
    rc = 0
    for page, open_tag, source_json, renderer in PAGES:
        rc = max(rc, process(page, open_tag, source_json, renderer, check_only))
    return rc


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
