r"""Publish the 2026-08-16 re-audits into games.json — the SOURCE OF TRUTH.

⛔ THE MISTAKE THIS FILE EXISTS TO PREVENT: data/games/<slug>.json and data/game_index.json are
GENERATED by build_game_index.py from games.json. Writing to them directly looks like it worked and
is silently erased on the next build. Everything must go into games.json, then build.

Two jobs:
  1. Serious Sam 19 -> 27 entries. The old list came from an unverified source and was missing the
     four VR rebuilds, the arcade VR build, the fourth licensed spin-off, the original Double D and
     the newest game.
  2. FromSoftware added as its own record — 129 releases, because the point is everything the studio
     made, not only the Souls games.

⛔ No hardware identity. ⛔ No source citations. Neutral language throughout.
Run build_game_index.py afterwards.
"""
import json
import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GAMES = ROOT / "data" / "games.json"
FS_SRC = Path(r"C:\game_optimization\fromsoftware_audit\master_list.json")

G1, G2, GDD, G3 = ("The First Encounter", "The Second Encounter", "Double D", "Serious Sam 3")


def slugify(s):
    s = unicodedata.normalize("NFKD", str(s or "")).encode("ascii", "ignore").decode()
    s = s.replace("'", "").replace("\u2019", "")
    return re.sub(r"-{2,}", "-", re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-").lower())


# \u2500\u2500 PUBLIC TEXT SANITISER \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
# \u26d4\u26d4 The audit files are MY WORKING NOTES. They carry priority markers, references to who said
# what, and \u2014 the part that actually matters \u2014 the NAMES OF SOURCES. We never cite a source, so a
# source name must never reach a page. This converts a working note into public prose, and main()
# refuses to write if anything slips through.
BANNED = re.compile(
    r"wikipedia|giant\s*bomb|gundam\s*wiki|mobygames|fandom|steam\s*community|"
    r"gg\.deals|codex|category sweep|2026-\d\d-\d\d|his rules?|his ruling|he said|"
    r"researched|according to|source", re.I)
MARKERS = re.compile(r"[\u2b50\u26d4\u26a0\u2705\u23f0\ufe0f]+\s*")


# Real acronyms and proper nouns keep their case; my SHOUTED emphasis does not.
KEEP_CASE = {"PS1", "PS2", "PS3", "PS4", "PS5", "PSP", "PSVR", "DS", "3DS", "PC", "VR", "HD",
             "HDR", "DLC", "XBLA", "GOTY", "RPG", "JRPG", "NPC", "AI", "UI", "FPS", "KF1"}
PROPER = {"JAPAN": "Japan", "JAPAN-ONLY": "Japan-only", "STEAM": "Steam", "SWITCH": "Switch",
          "SIXAXIS": "Sixaxis", "WESTERN": "Western", "AMERICAN": "American",
          "NORTH": "North", "AMERICA": "America", "PORTABLE": "Portable"}


def deshout(text):
    """Undo the ALL-CAPS emphasis I use in working notes \u2014 it reads as shouting on a page."""
    def fix(m):
        w = m.group(0)
        if w in KEEP_CASE:
            return w
        if w in PROPER:
            return PROPER[w]
        base = w.split("-")[0]
        if base in PROPER:
            return PROPER[base] + w[len(base):].lower()
        return w.lower()
    return re.sub(r"\b[A-Z][A-Z0-9'-]{2,}\b", fix, text)


def public(text):
    """Turn an internal audit note into neutral prose fit for the site."""
    if not text:
        return ""
    text = MARKERS.sub("", str(text)).replace("HIS RULING:", "").strip()
    # keep only sentences that carry no internal or source language
    parts = re.split(r"(?<=[.!?])\s+", text)
    keep = [p.strip() for p in parts if p.strip() and not BANNED.search(p)]
    out = deshout(" ".join(keep))
    out = re.sub(r"\s{2,}", " ", out).strip(" -\u2014")
    # a note that was ENTIRELY internal leaves nothing behind - better empty than leaking
    if len(out) <= 25:
        return ""
    return out[0].upper() + out[1:]


def entry(title, year, platform, role, caveat, groups=(), status="Not yet acquired",
          definitive="", emulation=""):
    return {
        "title": title, "release_year": year,
        "sami": {"chosen_platform": platform, "rating": "", "difficulty": "",
                 "completion_date": "", "notes": ""},
        "definitive_edition": definitive, "emulation": emulation, "status": status,
        "primary": platform, "secondary": "", "remaster_caveats": caveat,
        "version_groups": list(groups), "version_role": role,
        "all_releases": [], "confidence": "researched",
        "fidelity_vs_completeness_conflict": "",
    }


# ── 1. the eight Serious Sam entries the old list never had ────────────────────────────────
SS_NEW = [
    entry("Serious Sam Double D", 2011, "PC",
          "The original release, required alongside the expanded version rather than replaced "
          "by it.",
          "The later expanded version removed things — the golden guns are gone, the original rule "
          "that your own explosions hurt you was dropped, and the hardest difficulty is no longer "
          "available from the start. Anything removed means the earlier version still has to be "
          "played.",
          [GDD], status="Installed, not yet configured"),
    entry("Serious Sam: The Greek Encounter", 2012, "PC",
          "A standalone licensed spin-off, and the one most often left off franchise lists.",
          "An 8-bit top-down reimagining, commissioned and released alongside the other licensed "
          "spin-offs. It is an original game rather than a version of one, so it stands alone."),
    entry("Serious Sam VR: The First Encounter", 2016, "PC VR",
          "A complete rebuild of the first campaign for virtual reality, not a cut-down port.",
          "The whole game was recreated from start to finish with a movement system designed for "
          "VR. A rebuild on a fundamentally different device is its own game — the same reasoning "
          "that keeps the handheld version on this list.", [G1]),
    entry("Serious Sam VR: The Last Hope", 2017, "PC VR",
          "An original game — not a version of anything else in the series, and the home release "
          "of the two builds.",
          "Not a port at all, but a purpose-built arcade-style wave shooter with its own content. "
          "Nothing else in the series contains it.", ["The Last Hope"]),
    entry("Serious Sam VR: The Second Encounter", 2017, "PC VR",
          "The same ground-up rebuild applied to the second campaign.",
          "A complete recreation rather than a conversion, so it does not overlap with either the "
          "classic or the remade version of the same campaign.", [G2]),
    entry("Serious Sam VR: Arcade", 2017, "Arcade",
          "The arcade build of the same game, reworked for public installations rather than home "
          "headsets.",
          "Reworked for location-based play, with the session structure that suits a coin-operated "
          "venue rather than a living room. Being hard to obtain is not the same as not being "
          "required — availability decides when something gets played, never whether it belongs "
          "on the list.", ["The Last Hope"]),
    entry("Serious Sam 3 VR: BFE", 2017, "PC VR",
          "The virtual reality rebuild of the third mainline game.",
          "Rebuilt for VR rather than adapted, which makes it a distinct experience from the "
          "original.", [G3]),
    entry("Serious Sam: Shatterverse", 2026, "PC",
          "The newest entry in the series.",
          "A co-op roguelite built around alternate-dimension versions of Sam. Listed because it "
          "is part of the series; it will be assessed properly once it is out.",
          status="Releases 31 August 2026"),
]

# entries whose reasoning the re-audit changed
SS_REVISED = {
    "Serious Sam Double D XXL": dict(
        version_groups=[GDD],
        version_role="The expanded version, with the most content — but not a replacement for the "
                     "original.",
        remaster_caveats="Adds a great deal: many more weapon variants, new enemies, three vehicle "
                         "stages and co-op. But it also removed the golden guns and the original "
                         "rule that your own explosions hurt you, and it locks the hardest "
                         "difficulty behind finishing on normal. Because things were removed, both "
                         "versions are required."),
    "Serious Sam 3: BFE": dict(version_groups=[G3]),
}


def do_serious_sam(games):
    fr = next(f for f in games if f.get("franchise_slug") == "serious-sam")
    have = {e["title"] for e in fr["entries"]}
    added = [e for e in SS_NEW if e["title"] not in have]
    fr["entries"].extend(added)
    for e in fr["entries"]:
        if e["title"] in SS_REVISED:
            e.update(SS_REVISED[e["title"]])
        if e["title"] == "Serious Sam HD: The Second Encounter":
            c = (e.get("remaster_caveats") or "").rstrip()
            extra = ("Its add-on campaign belongs to this entry and must be installed with it: "
                     "three extra levels plus additional versus and survival maps.")
            if extra not in c:
                e["remaster_caveats"] = (c + " " + extra).strip()
    fr["entries"].sort(key=lambda e: (e["release_year"], e["title"]))
    fr["summary"] = ("Croteam's arena shooter series, played in release order with every version of "
                     "a title kept together — including the virtual reality rebuilds, the licensed "
                     "spin-offs, and the handheld and console releases that are usually left out.")
    return len(added), len(fr["entries"])


# ── 2. FromSoftware as its own record ──────────────────────────────────────────────────────
DECISION = {
    "one": "One playthrough covers this title — the chosen version has everything the others do "
           "and removes nothing.",
    "both": "Two playthroughs are required: no single release holds all the content, or the better "
            "looking one removed something.",
    "all-three": "All three are required — they are different games, not versions of one.",
}


# Entries whose internal note is mostly working commentary — written out properly for the public
# record instead of being machine-stripped down to a fragment.
FS_OVERRIDE = {
    "Mobile Suit Gundam U.C. Card Builder":
        "The only arcade machine the studio ever made, and one that is routinely left off "
        "English-language lists of their work. A card-driven strategy game with a single-player "
        "mission mode alongside its large networked battles, which is what keeps it on this list "
        "rather than in the discard pile with the purely competitive games.",
    "King's Field: Dark Side Box (compilation)":
        "A collection of the earlier games with extras. It contains nothing that the individual "
        "releases do not, so it is worth knowing about as a way to obtain them rather than as "
        "something separate to play.",
}


def do_fromsoftware(games):
    rows = json.loads(FS_SRC.read_text(encoding="utf-8"))
    rows.sort(key=lambda r: (r["year"], r.get("date", ""), r["en"]))
    entries = []
    for r in rows:
        gdec = r.get("group_decision")
        role = DECISION.get(gdec, "")
        if not role and r.get("kind") == "tool":
            role = ("A creation tool rather than a game, listed because it is part of what the "
                    "studio released.")
        entries.append({
            "title": r["en"], "release_year": r["year"],
            "sami": {"chosen_platform": r.get("platform", ""), "rating": "", "difficulty": "",
                     "completion_date": "", "notes": ""},
            "definitive_edition": "", "emulation": public(r.get("widescreen_route")),
            "status": public(r.get("availability")) or r.get("availability", "").lstrip("✅ "),
            "primary": r.get("platform", ""), "secondary": "",
            "remaster_caveats": (FS_OVERRIDE.get(r["en"])
                                 or public(r.get("group_why") or r.get("note"))
                                 # ⭐ never leave an entry blank — say plainly that it had one
                                 # release, which is itself the answer to "which version?"
                                 or "Released once, in a single version, so there is no edition "
                                    "question to settle — this is the only way it exists."),
            "version_groups": ([r["version_group"]] if r.get("version_group") else []),
            "version_role": role, "all_releases": [], "confidence": "researched",
            "fidelity_vs_completeness_conflict": "",
        })
    rec = {
        "franchise": "FromSoftware", "franchise_slug": "fromsoftware", "era": "1994 – present",
        "summary": ("Everything the studio has made, not only the Souls games — 129 releases across "
                    "three decades, taking in the mech series, the first-person dungeon crawlers, "
                    "the ninja games, licensed mecha work, puzzle and sudoku titles, handheld and "
                    "phone releases, one virtual reality game and one arcade machine. Versions of "
                    "the same title are kept together, and each entry says which other releases "
                    "are required and why."),
        "entries": entries,
    }
    games[:] = [f for f in games if f.get("franchise_slug") != "fromsoftware"]
    games.append(rec)
    return len(entries)


HARDWARE = re.compile(r"\b(RTX|GTX|Radeon|Ryzen|Core i[3579]|NVIDIA|GeForce|AMD|Intel|"
                      r"PG32UCDM|4090|5090)\b", re.I)


def audit_public_text(games):
    """⛔ Refuse to write if internal notes, source names or hardware reached a published record."""
    bad = []
    for fr in games:
        if fr.get("franchise_slug") not in ("serious-sam", "fromsoftware"):
            continue
        for e in fr.get("entries") or []:
            for field in ("remaster_caveats", "version_role", "emulation", "status",
                          "definitive_edition"):
                v = e.get(field) or ""
                if BANNED.search(v):
                    bad.append(f"{e['title']} / {field}: source or internal language")
                if HARDWARE.search(v):
                    bad.append(f"{e['title']} / {field}: hardware identity")
                if MARKERS.search(v):
                    bad.append(f"{e['title']} / {field}: working-note markers")
    return bad


def main():
    games = json.loads(GAMES.read_text(encoding="utf-8"))
    added, total = do_serious_sam(games)
    n = do_fromsoftware(games)

    problems = audit_public_text(games)
    if problems:
        print(f"  ⛔ REFUSING TO WRITE — {len(problems)} problem(s) in public text:")
        for p in problems[:20]:
            print(f"      {p}")
        return 1
    print("  ✅ public text clean: no source names, no internal markers, no hardware")

    games.sort(key=lambda f: (f.get("franchise") or "").lower())
    GAMES.write_text(json.dumps(games, ensure_ascii=False, indent=1),
                     encoding="utf-8", newline="\n")
    print(f"  Serious Sam: +{added} entries -> {total}")
    print(f"  FromSoftware: {n} entries added as a new record")
    print(f"  games.json now holds {len(games)} franchises")
    print("  ⇒ now run: python tools/build_game_index.py")


if __name__ == "__main__":
    raise SystemExit(main())
